CREATE TABLE IF NOT EXISTS tbl_merchant
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    name       VARCHAR(255),
    address    VARCHAR(255),
    CONSTRAINT pk_tbl_merchant PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS tbl_category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    name       VARCHAR(255),
    CONSTRAINT pk_tbl_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tbl_menu
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    name        VARCHAR(255),
    description VARCHAR(255),
    price       DOUBLE PRECISION                        NOT NULL,
    imageuri    VARCHAR(255),
    merchant_id BIGINT                                  NOT NULL,
    category_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_tbl_menu PRIMARY KEY (id)
);

ALTER TABLE tbl_menu
    ADD CONSTRAINT FK_TBL_MENU_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES tbl_category (id);

ALTER TABLE tbl_menu
    ADD CONSTRAINT FK_TBL_MENU_ON_MERCHANT FOREIGN KEY (merchant_id) REFERENCES tbl_merchant (id);